
version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_vps_project
    ports:
      - "5434:5434"
    volumes:
      - /postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "vinicius.politta1@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "15633:15632"
    depends_on:
      - postgres
